version: "3.7"
services:
  app:
    build:
      args:
        user: sammy
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: travellist
    container_name: travellist-app
    # restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - travellist

  db:
    image: mariadb
    container_name: travellist-db
    # restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      TZ: "Asia/Jakarta"
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - travellist

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: travellist-myadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - UPLOAD_LIMIT= 3000000000
    # restart: unless-stopped
    ports:
      - "2292:80"
    volumes:
      - /sessions
    links:
      - db
    networks:
      - travellist

  nginx:
    image: nginx:alpine
    container_name: travellist-nginx
    # restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - travellist

networks:
  travellist:
    driver: bridge
